# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20190406133626) do

  create_table "bacs", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci" do |t|
    t.string "a1"
    t.string "a2"
    t.string "a3"
    t.string "a4"
    t.string "a5"
    t.string "a6"
    t.string "a7"
    t.string "a8"
    t.string "a9"
    t.string "a10"
    t.string "a11"
    t.string "a12"
    t.string "a13"
    t.string "a14"
    t.string "a15"
    t.string "a16"
    t.string "a17"
    t.string "a18"
    t.string "a19"
    t.string "a20"
    t.string "a21"
    t.string "a22"
    t.string "a23"
    t.string "a24"
    t.string "a25"
    t.string "a26"
    t.string "a27"
    t.string "a28"
    t.string "a29"
    t.string "a30"
    t.string "a31"
    t.string "a32"
    t.string "a33"
    t.string "a34"
    t.string "a35"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "chas", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci" do |t|
    t.string "a1"
    t.string "a2"
    t.string "a3"
    t.string "a4"
    t.string "a5"
    t.string "a6"
    t.string "a7"
    t.string "a8"
    t.string "a9"
    t.string "a10"
    t.string "a11"
    t.string "a12"
    t.string "a13"
    t.string "a14"
    t.string "a15"
    t.string "a16"
    t.string "a17"
    t.string "a18"
    t.string "a19"
    t.string "a20"
    t.string "a21"
    t.string "a22"
    t.string "a23"
    t.string "a24"
    t.string "a25"
    t.string "a26"
    t.string "a27"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "cybs", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci" do |t|
    t.string "a1"
    t.string "a2"
    t.string "a3"
    t.string "a4"
    t.string "a5"
    t.string "a6"
    t.string "a7"
    t.string "a8"
    t.string "a9"
    t.string "a10"
    t.string "a11"
    t.string "a12"
    t.string "a13"
    t.string "a14"
    t.string "a15"
    t.string "a16"
    t.string "a17"
    t.string "a18"
    t.string "a19"
    t.string "a20"
    t.string "a21"
    t.string "a22"
    t.string "a23"
    t.string "a24"
    t.string "a25"
    t.string "a26"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "joas", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci" do |t|
    t.string "a1"
    t.string "a2"
    t.string "a3"
    t.string "a4"
    t.string "a5"
    t.string "a6"
    t.string "a7"
    t.string "a8"
    t.string "a9"
    t.string "a10"
    t.string "a11"
    t.string "a12"
    t.string "a13"
    t.string "a14"
    t.string "a15"
    t.string "a16"
    t.string "a17"
    t.string "a18"
    t.string "a19"
    t.string "a20"
    t.string "a21"
    t.string "a22"
    t.string "a23"
    t.string "a24"
    t.string "a25"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "jra_db", id: false, force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci" do |t|
    t.string "code"
    t.text "year"
    t.text "the_time"
    t.text "day"
    t.text "race"
    t.text "race_day"
    t.text "race_time"
    t.text "distance"
    t.text "baba"
    t.text "turn"
    t.text "track"
    t.text "class"
    t.text "cond"
    t.text "race_condition"
    t.text "weight"
    t.text "grade"
  end

  create_table "jras", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci" do |t|
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "kabs", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci" do |t|
    t.string "a1"
    t.string "a2"
    t.string "a3"
    t.string "a4"
    t.string "a5"
    t.string "a6"
    t.string "a7"
    t.string "a8"
    t.string "a9"
    t.string "a10"
    t.string "a11"
    t.string "a12"
    t.string "a13"
    t.string "a14"
    t.string "a15"
    t.string "a16"
    t.string "a17"
    t.string "a18"
    t.string "a19"
    t.string "a20"
    t.string "a21"
    t.string "a22"
    t.string "a23"
    t.string "a24"
    t.string "a25"
    t.string "a26"
    t.string "a27"
    t.string "a28"
    t.string "a29"
    t.string "a30"
    t.string "a31"
    t.string "a32"
    t.string "a33"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "keibas", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci" do |t|
    t.string "race"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "kkas", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci" do |t|
    t.string "a1"
    t.string "a2"
    t.string "a3"
    t.string "a4"
    t.string "a5"
    t.string "a6"
    t.string "a7"
    t.string "a8"
    t.string "a9"
    t.string "a10"
    t.string "a11"
    t.string "a12"
    t.string "a13"
    t.string "a14"
    t.string "a15"
    t.string "a16"
    t.string "a17"
    t.string "a18"
    t.string "a19"
    t.string "a20"
    t.string "a21"
    t.string "a22"
    t.string "a23"
    t.string "a24"
    t.string "a25"
    t.string "a26"
    t.string "a27"
    t.string "a28"
    t.string "a29"
    t.string "a30"
    t.string "a31"
    t.string "a32"
    t.string "a33"
    t.string "a34"
    t.string "a35"
    t.string "a36"
    t.string "a37"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "kyis", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci" do |t|
    t.text "a1"
    t.text "a2"
    t.text "a3"
    t.text "a4"
    t.text "a5"
    t.text "a6"
    t.text "a7"
    t.text "a8"
    t.text "a9"
    t.text "a10"
    t.text "a11"
    t.text "a12"
    t.text "a13"
    t.text "a14"
    t.text "a15"
    t.text "a16"
    t.text "a17"
    t.text "a18"
    t.text "a19"
    t.text "a20"
    t.text "a21"
    t.text "a22"
    t.text "a23"
    t.text "a24"
    t.text "a25"
    t.text "a26"
    t.text "a27"
    t.text "a28"
    t.text "a29"
    t.text "a30"
    t.text "a31"
    t.text "a32"
    t.text "a33"
    t.text "a34"
    t.text "a35"
    t.text "a36"
    t.text "a37"
    t.text "a38"
    t.text "a39"
    t.text "a40"
    t.text "a41"
    t.text "a42"
    t.text "a43"
    t.text "a44"
    t.text "a45"
    t.text "a46"
    t.text "a47"
    t.text "a48"
    t.text "a49"
    t.text "a50"
    t.text "a51"
    t.text "a52"
    t.text "a53"
    t.text "a54"
    t.text "a55"
    t.text "a56"
    t.text "a57"
    t.text "a58"
    t.text "a59"
    t.text "a60"
    t.text "a61"
    t.text "a62"
    t.text "a63"
    t.text "a64"
    t.text "a65"
    t.text "a66"
    t.text "a67"
    t.text "a68"
    t.text "a69"
    t.text "a70"
    t.text "a71"
    t.text "a72"
    t.text "a73"
    t.text "a74"
    t.text "a75"
    t.text "a76"
    t.text "a77"
    t.text "a78"
    t.text "a79"
    t.text "a80"
    t.text "a81"
    t.text "a82"
    t.text "a83"
    t.text "a84"
    t.text "a85"
    t.text "a86"
    t.text "a87"
    t.text "a88"
    t.text "a89"
    t.text "a90"
    t.text "a91"
    t.text "a92"
    t.text "a93"
    t.text "a94"
    t.text "a95"
    t.text "a96"
    t.text "a97"
    t.text "a98"
    t.text "a99"
    t.text "a100"
    t.text "a101"
    t.text "a102"
    t.text "a103"
    t.text "a104"
    t.text "a105"
    t.text "a106"
    t.text "a107"
    t.text "a108"
    t.text "a109"
    t.text "a110"
    t.text "a111"
    t.text "a112"
    t.text "a113"
    t.text "a114"
    t.text "a115"
    t.text "a116"
    t.text "a117"
    t.text "a118"
    t.text "a119"
    t.text "a120"
    t.text "a121"
    t.text "a122"
    t.text "a123"
    t.text "a124"
    t.text "a125"
    t.text "a126"
    t.text "a127"
    t.text "a128"
    t.text "a129"
    t.text "a130"
    t.text "a131"
    t.text "a132"
    t.text "a133"
    t.text "a134"
    t.text "a135"
    t.text "a136"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "kyousous", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci" do |t|
    t.string "titi"
    t.string "haha"
    t.string "hahatiti"
    t.string "seibetu"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "ots", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci" do |t|
    t.string "a1"
    t.string "a2"
    t.string "a3"
    t.string "a4"
    t.string "a5"
    t.string "a6"
    t.string "a7"
    t.string "a8"
    t.string "a9"
    t.string "a10"
    t.string "a11"
    t.string "a12"
    t.string "a13"
    t.string "a14"
    t.string "a15"
    t.string "a16"
    t.string "a17"
    t.string "a18"
    t.string "a19"
    t.string "a20"
    t.string "a21"
    t.string "a22"
    t.string "a23"
    t.string "a24"
    t.string "a25"
    t.string "a26"
    t.string "a27"
    t.string "a28"
    t.string "a29"
    t.string "a30"
    t.string "a31"
    t.string "a32"
    t.string "a33"
    t.string "a34"
    t.string "a35"
    t.string "a36"
    t.string "a37"
    t.string "a38"
    t.string "a39"
    t.string "a40"
    t.string "a41"
    t.string "a42"
    t.string "a43"
    t.string "a44"
    t.string "a45"
    t.string "a46"
    t.string "a47"
    t.string "a48"
    t.string "a49"
    t.string "a50"
    t.string "a51"
    t.string "a52"
    t.string "a53"
    t.string "a54"
    t.string "a55"
    t.string "a56"
    t.string "a57"
    t.string "a58"
    t.string "a59"
    t.string "a60"
    t.string "a61"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "ous", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci" do |t|
    t.string "a1"
    t.string "a2"
    t.string "a3"
    t.string "a4"
    t.string "a5"
    t.string "a6"
    t.string "a7"
    t.string "a8"
    t.string "a9"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "ows", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci" do |t|
    t.string "a1"
    t.string "a2"
    t.string "a3"
    t.string "a4"
    t.string "a5"
    t.string "a6"
    t.string "a7"
    t.string "a8"
    t.string "a9"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "ozs", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci" do |t|
    t.string "a1"
    t.string "a2"
    t.string "a3"
    t.string "a4"
    t.string "a5"
    t.string "a6"
    t.string "a7"
    t.string "a8"
    t.string "a9"
    t.string "a10"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "syubobas", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci" do |t|
    t.string "titi"
    t.string "haha"
    t.string "hahatiti"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "ukcs", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci" do |t|
    t.string "a1"
    t.string "a2"
    t.string "a3"
    t.string "a4"
    t.string "a5"
    t.string "a6"
    t.string "a7"
    t.string "a8"
    t.string "a9"
    t.string "a10"
    t.string "a11"
    t.string "a12"
    t.string "a13"
    t.string "a14"
    t.string "a15"
    t.string "a16"
    t.string "a17"
    t.string "a18"
    t.string "a19"
    t.string "a20"
    t.string "a21"
    t.string "a22"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "umas", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci" do |t|
    t.string "name"
    t.string "kisyu"
    t.string "tyoukyousi"
    t.string "zensou1"
    t.string "zensou2"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "zeds", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci" do |t|
    t.string "a1"
    t.string "a2"
    t.string "a3"
    t.string "a4"
    t.string "a5"
    t.string "a6"
    t.string "a7"
    t.string "a8"
    t.string "a9"
    t.string "a10"
    t.string "a11"
    t.string "a12"
    t.string "a13"
    t.string "a14"
    t.string "a15"
    t.string "a16"
    t.string "a17"
    t.string "a18"
    t.string "a19"
    t.string "a20"
    t.string "a21"
    t.string "a22"
    t.string "a23"
    t.string "a24"
    t.string "a25"
    t.string "a26"
    t.string "a27"
    t.string "a28"
    t.string "a29"
    t.string "a30"
    t.string "a31"
    t.string "a32"
    t.string "a33"
    t.string "a34"
    t.string "a35"
    t.string "a36"
    t.string "a37"
    t.string "a38"
    t.string "a39"
    t.string "a40"
    t.string "a41"
    t.string "a42"
    t.string "a43"
    t.string "a44"
    t.string "a45"
    t.string "a46"
    t.string "a47"
    t.string "a48"
    t.string "a49"
    t.string "a50"
    t.string "a51"
    t.string "a52"
    t.string "a53"
    t.string "a54"
    t.string "a55"
    t.string "a56"
    t.string "a57"
    t.string "a58"
    t.string "a59"
    t.string "a60"
    t.string "a61"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "zkbs", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci" do |t|
    t.string "a1"
    t.string "a2"
    t.string "a3"
    t.string "a4"
    t.string "a5"
    t.string "a6"
    t.string "a7"
    t.string "a8"
    t.string "a9"
    t.string "a10"
    t.string "a11"
    t.string "a12"
    t.string "a13"
    t.string "a14"
    t.string "a15"
    t.string "a16"
    t.string "a17"
    t.string "a18"
    t.string "a19"
    t.string "a20"
    t.string "a21"
    t.string "a22"
    t.string "a23"
    t.string "a24"
    t.string "a25"
    t.string "a26"
    t.string "a27"
    t.string "a28"
    t.string "a29"
    t.string "a30"
    t.string "a31"
    t.string "a32"
    t.string "a33"
    t.string "a34"
    t.string "a35"
    t.string "a36"
    t.string "a37"
    t.string "a38"
    t.string "a39"
    t.string "a40"
    t.string "a41"
    t.string "a42"
    t.string "a43"
    t.string "a44"
    t.string "a45"
    t.string "a46"
    t.string "a47"
    t.string "a48"
    t.string "a49"
    t.string "a50"
    t.string "a51"
    t.string "a52"
    t.string "a53"
    t.string "a54"
    t.string "a55"
    t.string "a56"
    t.string "a57"
    t.string "a58"
    t.string "a59"
    t.string "a60"
    t.string "a61"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

end
